# Explore the ParlTrack dumps
Raw look at every file in this folder: the first records as-is, then the fields (columns) each file has.
Files are streamed, never loaded whole.

In [1]:
import io, json
from collections import Counter
from pathlib import Path
import pandas as pd
import zstandard

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

FOLDER = Path(".")
FILES = ["ep_amendments", "ep_plenary_amendments", "ep_meps", "ep_dossiers"]

def records(name, n=None):
    """Yield parsed records from <name>.json or <name>.json.zst, one per line."""
    plain, packed = FOLDER / f"{name}.json", FOLDER / f"{name}.json.zst"
    fh = open(plain, encoding="utf-8") if plain.exists() else \
        io.TextIOWrapper(zstandard.ZstdDecompressor().stream_reader(open(packed, "rb")), encoding="utf-8")
    with fh:
        count = 0
        for line in fh:
            line = line.strip()
            if not line or line == "]":
                continue
            yield json.loads(line[1:])  # strip leading '[' or ','
            count += 1
            if n and count >= n:
                return

def show_raw(name, n=2):
    print(f"===== {name}: first {n} records =====")
    for r in records(name, n):
        print(json.dumps(r, indent=1, ensure_ascii=False))
        print("-" * 80)

def fields(name, sample=2000):
    """Which top-level fields exist, how often, their type and an example value."""
    seen, types, example = Counter(), {}, {}
    total = 0
    for r in records(name, sample):
        total += 1
        for k, v in r.items():
            seen[k] += 1
            types.setdefault(k, type(v).__name__)
            example.setdefault(k, json.dumps(v, ensure_ascii=False)[:120])
    return pd.DataFrame([{"field": k, "present_%": round(100 * c / total, 1), "type": types[k], "example": example[k]}
                         for k, c in seen.most_common()])

## `ep_amendments`

In [2]:
show_raw("ep_amendments", n=2)

===== ep_amendments: first 2 records =====
{
 "src": "http://www.europarl.europa.eu/sides/getDoc.do?pubRef=-//EP//NONSGML+COMPARL+PE-529.899+01+DOC+PDF+V0//EN&language=EN",
 "peid": "PE529.899v01-00",
 "reference": "2014/2021(INI)",
 "date": "2014-03-05T00:00:00",
 "committee": [
  "AFET"
 ],
 "seq": 1,
 "id": "PE529.899-1",
 "orig_lang": "en",
 "new": [
  "- having regard to its resolution of 13",
  "December 20071 on Justice for the",
  "'Comfort Women' (sex slaves in Asia",
  "before and during World War II) as well",
  "as the statements by Japanese Chief",
  "Cabinet Secretary Yohei Kono in 1993",
  "and by the then Prime Minister Tomiichi",
  "Murayama in 1995, the resolutions of the",
  "Japanese parliament (the Diet) of 1995",
  "and 2005 expressing apologies for",
  "wartime victims, including victims of the",
  "'comfort women' system,",
  "_______________________",
  "1",
  "OJ C 323E, 18.12.2008, p.531"
 ],
 "authors": "Reinhard Bütikofer on behalf of the Verts/ALE Group",
 "meps": [
  96739
 ],
 "location": [
  [
   "Motion for a resolution",
   "Citation 6 a (new)"
  ]
 ],
 "meta": {
  "created": "2019-07-03T05:06:17"
 },
 "changes": {}
}
--------------------------------------------------------------------------------
{
 "src": "http://www.europarl.europa.eu/sides/getDoc.do?pubRef=-//EP//NONSGML+COMPARL+PE-529.863+01+DOC+PDF+V0//EN&language=EN",
 "peid": "PE529.863v01-00",
 "reference": "2014/2016(INI)",
 "date": "2014-02-27T00:00:00",
 "committee": [
  "AFET"
 ],
 "seq": 1,
 "id": "PE529.863-1",
 "orig_lang": "en",
 "new": [
  "- having regard to the Statement by the",
  "Vice-President of the Commission/ High",
  "Representative of the Union for Foreign",
  "affairs and Security Policy (VP/HR)",
  "Catherine Ashton of 20 March 2013 on",
  "the Magnitsky case in the Russian",
  "Federation,"
 ],
 "authors": "Jacek Protasiewicz",
 "meps": [
  23782
 ],
 "location": [
  [
   "Motion for a resolution",
   "Citation 4 a (new)"
  ]
 ],
 "meta": {
  "created": "2019-07-03T05:06:17"
 },
 "changes": {}
}
--------------------------------------------------------------------------------

In [3]:
fields("ep_amendments")

,field,present_%,type,example
0,src,100.0,str,"""http://www.europarl.europa.eu/sides/getDoc.do?pubRef=-//EP//NONSGML+COMPARL+PE-529.899+01+DOC+PDF+V0//EN&language=EN"""
1,peid,100.0,str,"""PE529.899v01-00"""
2,reference,100.0,str,"""2014/2021(INI)"""
3,date,100.0,str,"""2014-03-05T00:00:00"""
4,committee,100.0,list,"[""AFET""]"
5,seq,100.0,int,1
6,id,100.0,str,"""PE529.899-1"""
7,orig_lang,100.0,str,"""en"""
8,authors,100.0,str,"""Reinhard Bütikofer on behalf of the Verts/ALE Group"""
9,location,100.0,list,"[[""Motion for a resolution"", ""Citation 6 a (new)""]]"
10,meta,100.0,dict,"{""created"": ""2019-07-03T05:06:17""}"
11,changes,100.0,dict,{}
12,new,99.9,list,"[""- having regard to its resolution of 13"", ""December 20071 on Justice for the"", ""'Comfort Women' (sex slaves in Asi..."
13,meps,99.8,list,[96739]
14,old,69.5,list,"[""A. whereas the European Neighbourhood"", ""Policy (ENP), in particular the Eastern"", ""Partnership (EaP), aims to ext..."
15,justification,1.0,str,""" To emphasize the EU trade and micro financial assistance competence as the Agreement was\n signed before t..."
16,compromise,0.2,list,"["" on behalf of the Verts/ALE Group""]"

## `ep_plenary_amendments`

In [4]:
show_raw("ep_plenary_amendments", n=2)

===== ep_plenary_amendments: first 2 records =====
{
 "seq": "1",
 "location": [
  "Recital 1"
 ],
 "old": [
  "(1) Claiming to be “green” and sustainable has become a competitiveness factor, with green products registering greater growth than standard products. If goods and services offered and purchased on the internal market are not as environmentally friendly as presented, this would mislead the consumers, hamper the green transition and prevent the reduction of negative environmental impacts. The potential of green markets is not fully realised. Different requirements imposed by national legislation or private initiatives regulating environmental claims create a burden for companies in cross-border trade, as they need to comply with different requirements in each Member State. This affects their capacity to operate in and take advantage of the internal market. At the same time, market participants have difficulties with identifying reliable environmental claims and making optimal purchasing decisions on the internal market. With a proliferation of different labels and calculation methods on the market, it is difficult for consumers, businesses, investors and stakeholders to establish if claims are trustworthy."
 ],
 "new": [
  "(1) Claiming to be “green” and sustainable has become a competitiveness factor, with green products registering greater growth than standard products as consumer interest grows . If goods and services offered and purchased on the internal market are not as environmentally friendly as presented, this would mislead the consumers, hamper the green transition , and prevent the reduction of negative environmental impacts. The potential of green markets is not fully realised. Different requirements imposed by national legislation or private initiatives regulating environmental claims create a burden for companies in cross-border trade, as they need to comply with different requirements in each Member State. This affects their capacity to operate in and take advantage of the internal market. At the same time, market participants have difficulties with identifying reliable environmental claims and making optimal purchasing decisions on the internal market. With a proliferation of different labels and calculation methods on the market, it is difficult for consumers, businesses, investors and stakeholders to establish if claims are trustworthy."
 ],
 "src_type": "html",
 "reference": "2023/0085(COD)",
 "adoc_src": "https://www.europarl.europa.eu/doceo/document/A-9-2024-0056_EN.html",
 "id": "A9-0056/2024-1",
 "meta": {
  "created": "2024-12-31T00:58:07+00:00"
 },
 "changes": {}
}
--------------------------------------------------------------------------------
{
 "seq": "1",
 "location": [
  "Recital 7"
 ],
 "old": [
  "(7) This Regulation should apply to all requests issued within the framework of criminal proceedings. Criminal proceedings is an autonomous concept of Union law interpreted by the Court of Justice of the European Union, notwithstanding the case law of the European Court of Human Rights, starting from the time when persons are informed by the competent authorities of a Member State that they are suspected or accused of having committed a criminal offence until the conclusion of those proceedings, to be understood as the final determination of the question whether the suspect or accused person has committed the criminal offence, including, where applicable, sentencing and the resolution of any appeal."
 ],
 "new": [
  "(7) This Regulation should apply to all requests issued within the framework of criminal proceedings."
 ],
 "src_type": "html",
 "reference": "2023/0093(COD)",
 "adoc_src": "https://www.europarl.europa.eu/doceo/document/A-9-2024-0008_EN.html",
 "id": "A9-0008/2024-1",
 "meta": {
  "created": "2024-12-21T00:58:33+00:00"
 },
 "changes": {}
}
--------------------------------------------------------------------------------

In [5]:
fields("ep_plenary_amendments")

,field,present_%,type,example
0,seq,100.0,str,"""1"""
1,location,100.0,list,"[""Recital 1""]"
2,src_type,100.0,str,"""html"""
3,reference,100.0,str,"""2023/0085(COD)"""
4,adoc_src,100.0,str,"""https://www.europarl.europa.eu/doceo/document/A-9-2024-0056_EN.html"""
5,id,100.0,str,"""A9-0056/2024-1"""
6,meta,100.0,dict,"{""created"": ""2024-12-31T00:58:07+00:00""}"
7,changes,100.0,dict,{}
8,new,99.8,list,"[""(1) Claiming to be “green” and sustainable has become a competitiveness factor, with green products registering gr..."
9,old,66.8,list,"[""(1) Claiming to be “green” and sustainable has become a competitiveness factor, with green products registering gr..."
10,src,25.1,str,"""https://www.europarl.europa.eu/doceo/document/A-9-2023-0148-AM-001-020_EN.pdf"""
11,peid,25.1,str,"""PE760.530"""
12,date,25.1,str,"""2024-03-26T00:00:00"""
13,committee,24.6,str,"""LIBE"""
14,justification,1.2,str,"""(Article 8 becomes Article 15c)"""
15,orig_lang,0.5,str,"""en"""
16,authors,0.5,str,"""Pedro Silva Pereira on behalf of the S&D Group"""
17,meps,0.5,list,[124747]
18,dossier,0.5,dict,"{""type"": ""Report"", ""aref"": ""A9-0052/2023"", ""meps"": [124747]}"
19,vote_ids,0.1,list,[166305]

## `ep_meps`

In [6]:
show_raw("ep_meps", n=1)  # MEP/dossier records are long

===== ep_meps: first 1 records =====
{
 "UserID": 2307,
 "Name": {
  "full": "Hubert PIRKER",
  "sur": "Hubert",
  "family": "PIRKER",
  "aliases": [
   "Hubert PIRKER",
   "PIRKER",
   "PIRKER Hubert"
  ]
 },
 "Photo": "https://www.europarl.europa.eu/mepphoto/2307.jpg",
 "meta": {
  "url": "http://www.europarl.europa.eu/meps/en/2307/name/cv",
  "updated": "2019-07-12T18:57:20"
 },
 "active": false,
 "Birth": {
  "date": "1948-10-03T00:00:00",
  "place": "Gries"
 },
 "Groups": [
  {
   "role": "Member",
   "Organization": "Group of the European People's Party (Christian-Democratic Group)",
   "groupid": "PPE",
   "start": "1996-11-11T00:00:00",
   "end": "1999-07-19T00:00:00"
  },
  {
   "role": "Member",
   "Organization": "Group of the European People's Party (Christian Democrats) and European Democrats",
   "groupid": "PPE-DE",
   "start": "1999-07-20T00:00:00",
   "end": "2004-07-19T00:00:00"
  },
  {
   "role": "Member",
   "Organization": "Group of the European People's Party (Christian Democrats) and European Democrats",
   "groupid": "PPE-DE",
   "start": "2006-02-01T00:00:00",
   "end": "2009-07-13T00:00:00"
  },
  {
   "role": "Member",
   "Organization": "Group of the European People's Party (Christian Democrats)",
   "groupid": "PPE",
   "start": "2011-03-31T00:00:00",
   "end": "2014-06-30T00:00:00"
  }
 ],
 "Constituencies": [
  {
   "party": "Österreichische Volkspartei",
   "country": "Austria",
   "start": "1996-11-11T00:00:00",
   "end": "1999-07-19T00:00:00",
   "term": 4
  },
  {
   "party": "Österreichische Volkspartei",
   "country": "Austria",
   "start": "1999-07-20T00:00:00",
   "end": "2004-07-19T00:00:00",
   "term": 5
  },
  {
   "party": "Österreichische Volkspartei - Liste Ursula Stenzel",
   "country": "Austria",
   "start": "2006-02-01T00:00:00",
   "end": "2009-07-13T00:00:00",
   "term": 6
  },
  {
   "party": "Österreichische Volkspartei",
   "country": "Austria",
   "start": "2011-03-31T00:00:00",
   "end": "2014-06-30T00:00:00",
   "term": 7
  }
 ],
 "Committees": [
  {
   "role": "Member",
   "Organization": "Committee on Civil Liberties and Internal Affairs",
   "start": "1996-11-14T00:00:00",
   "end": "1997-01-15T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Social Affairs and Employment",
   "start": "1996-11-14T00:00:00",
   "end": "1997-01-15T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Member",
   "Organization": "Committee on the Rules of Procedure, the Verification of Credentials and Immunities",
   "start": "1996-11-14T00:00:00",
   "end": "1997-01-15T00:00:00",
   "term": 4,
   "abbr": "REGL"
  },
  {
   "role": "Member",
   "Organization": "Committee on Civil Liberties and Internal Affairs",
   "start": "1997-01-16T00:00:00",
   "end": "1999-07-19T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Employment and Social Affairs",
   "start": "1997-01-16T00:00:00",
   "end": "1999-07-19T00:00:00",
   "term": 4,
   "abbr": "EMPL"
  },
  {
   "role": "Member",
   "Organization": "Committee on the Rules of Procedure, the Verification of Credentials and Immunities",
   "start": "1997-01-16T00:00:00",
   "end": "1999-07-19T00:00:00",
   "term": 4,
   "abbr": "REGL"
  },
  {
   "role": "Member",
   "Organization": "Committee on Citizens' Freedoms and Rights, Justice and Home Affairs",
   "start": "1999-07-21T00:00:00",
   "end": "2002-01-14T00:00:00",
   "term": 5,
   "abbr": "LIBE"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Employment and Social Affairs",
   "start": "1999-07-21T00:00:00",
   "end": "2002-01-14T00:00:00",
   "term": 5,
   "abbr": "EMPL"
  },
  {
   "role": "Member",
   "Organization": "Temporary committee on the Echelon interception system",
   "start": "2000-07-06T00:00:00",
   "end": "2001-09-05T00:00:00",
   "term": 5,
   "abbr": "ECHE"
  },
  {
   "role": "Member",
   "Organization": "Committee on Citizens' Freedoms and Rights, Justice and Home Affairs",
   "start": "2002-01-17T00:00:00",
   "end": "2004-07-19T00:00:00",
   "term": 5,
   "abbr": "LIBE"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Employment and Social Affairs",
   "start": "2002-01-17T00:00:00",
   "end": "2004-07-19T00:00:00",
   "term": 5,
   "abbr": "EMPL"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Civil Liberties, Justice and Home Affairs",
   "start": "2006-02-02T00:00:00",
   "end": "2007-01-14T00:00:00",
   "term": 6,
   "abbr": "LIBE"
  },
  {
   "role": "Member",
   "Organization": "Committee on Foreign Affairs",
   "start": "2006-02-02T00:00:00",
   "end": "2007-01-14T00:00:00",
   "term": 6,
   "abbr": "AFET"
  },
  {
   "role": "Member",
   "Organization": "Subcommittee on Security and Defence",
   "start": "2006-02-02T00:00:00",
   "end": "2007-01-14T00:00:00",
   "term": 6,
   "abbr": "SEDE"
  },
  {
   "role": "Member",
   "Organization": "Temporary Committee on the alleged use of European countries by the CIA for the transport and illegal detention of prisoners",
   "start": "2006-02-02T00:00:00",
   "end": "2007-02-14T00:00:00",
   "term": 6,
   "abbr": "TDIP"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Civil Liberties, Justice and Home Affairs",
   "start": "2007-01-15T00:00:00",
   "end": "2007-01-30T00:00:00",
   "term": 6,
   "abbr": "LIBE"
  },
  {
   "role": "Member",
   "Organization": "Committee on Foreign Affairs",
   "start": "2007-01-15T00:00:00",
   "end": "2007-01-30T00:00:00",
   "term": 6,
   "abbr": "AFET"
  },
  {
   "role": "Member",
   "Organization": "Subcommittee on Security and Defence",
   "start": "2007-01-15T00:00:00",
   "end": "2007-01-30T00:00:00",
   "term": 6,
   "abbr": "SEDE"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Civil Liberties, Justice and Home Affairs",
   "start": "2007-01-31T00:00:00",
   "end": "2009-07-13T00:00:00",
   "term": 6,
   "abbr": "LIBE"
  },
  {
   "role": "Member",
   "Organization": "Committee on Foreign Affairs",
   "start": "2007-01-31T00:00:00",
   "end": "2009-07-13T00:00:00",
   "term": 6,
   "abbr": "AFET"
  },
  {
   "role": "Member",
   "Organization": "Subcommittee on Security and Defence",
   "start": "2007-01-31T00:00:00",
   "end": "2009-07-13T00:00:00",
   "term": 6,
   "abbr": "SEDE"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Civil Liberties, Justice and Home Affairs",
   "start": "2011-04-06T00:00:00",
   "end": "2012-01-18T00:00:00",
   "term": 7,
   "abbr": "LIBE"
  },
  {
   "role": "Member",
   "Organization": "Committee on Transport and Tourism",
   "start": "2011-04-06T00:00:00",
   "end": "2012-01-18T00:00:00",
   "term": 7,
   "abbr": "TRAN"
  },
  {
   "role": "Substitute",
   "Organization": "Committee on Civil Liberties, Justice and Home Affairs",
   "start": "2012-01-19T00:00:00",
   "end": "2014-06-30T00:00:00",
   "term": 7,
   "abbr": "LIBE"
  },
  {
   "role": "Member",
   "Organization": "Committee on Transport and Tourism",
   "start": "2012-01-19T00:00:00",
   "end": "2014-06-30T00:00:00",
   "term": 7,
   "abbr": "TRAN"
  },
  {
   "role": "Member",
   "Organization": "Special Committee on Organised Crime, Corruption and Money Laundering",
   "start": "2012-03-28T00:00:00",
   "end": "2013-10-23T00:00:00",
   "term": 7,
   "abbr": "CRIM"
  }
 ],
 "Delegations": [
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Member States of ASEAN, South-east Asia and the Republic of Korea",
   "start": "1996-11-14T00:00:00",
   "end": "1997-01-15T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Member States of ASEAN, South-east Asia and the Republic of Korea",
   "start": "1997-01-16T00:00:00",
   "end": "1997-10-13T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Substitute",
   "Organization": "Delegation for relations with Slovenia",
   "start": "1997-01-16T00:00:00",
   "end": "1999-02-23T00:00:00",
   "term": 4
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Member States of ASEAN, South-east Asia and the Republic of Korea",
   "start": "1997-10-14T00:00:00",
   "end": "1999-02-23T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Member States of ASEAN, South-east Asia and the Republic of Korea",
   "start": "1999-02-24T00:00:00",
   "end": "1999-07-19T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Substitute",
   "Organization": "Delegation to the EU-Slovenia Joint Parliamentary Committee",
   "start": "1999-02-24T00:00:00",
   "end": "1999-07-20T00:00:00",
   "term": 4,
   "abbr": ""
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Member States of ASEAN, South-east Asia and the Republic of Korea",
   "start": "1999-10-06T00:00:00",
   "end": "2002-01-14T00:00:00",
   "term": 5,
   "abbr": ""
  },
  {
   "role": "Substitute",
   "Organization": "Delegation to the EU-Slovenia Joint Parliamentary Committee",
   "start": "1999-10-08T00:00:00",
   "end": "2002-01-14T00:00:00",
   "term": 5,
   "abbr": ""
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Member States of ASEAN, south-east Asia and the Republic of Korea",
   "start": "2002-02-07T00:00:00",
   "end": "2004-07-19T00:00:00",
   "term": 5,
   "abbr": ""
  },
  {
   "role": "Substitute",
   "Organization": "Delegation to the EU-Slovenia Joint Parliamentary Committee",
   "start": "2002-03-07T00:00:00",
   "end": "2004-04-30T00:00:00",
   "term": 5,
   "abbr": ""
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the Korean Peninsula",
   "start": "2006-02-02T00:00:00",
   "end": "2006-03-20T00:00:00",
   "term": 6,
   "abbr": "DKOR"
  },
  {
   "role": "Chair",
   "Organization": "Delegation for relations with the Korean Peninsula",
   "start": "2006-03-21T00:00:00",
   "end": "2007-03-13T00:00:00",
   "term": 6,
   "abbr": "DKOR"
  },
  {
   "role": "Chair",
   "Organization": "Delegation for relations with the Korean Peninsula",
   "start": "2007-03-14T00:00:00",
   "end": "2009-07-13T00:00:00",
   "term": 6,
   "abbr": "DKOR"
  },
  {
   "role": "Substitute",
   "Organization": "Delegation to the EU-Croatia Joint Parliamentary Committee",
   "start": "2011-04-06T00:00:00",
   "end": "2013-06-30T00:00:00",
   "term": 7,
   "abbr": "D-HR"
  },
  {
   "role": "Substitute",
   "Organization": "Delegation for relations with India",
   "start": "2011-04-06T00:00:00",
   "end": "2014-06-30T00:00:00",
   "term": 7,
   "abbr": "D-IN"
  },
  {
   "role": "Substitute",
   "Organization": "Delegation for relations with the countries of Southeast Asia and the Association of Southeast Asian Nations (ASEAN)",
   "start": "2013-07-08T00:00:00",
   "end": "2013-10-08T00:00:00",
   "term": 7,
   "abbr": "DASE"
  },
  {
   "role": "Member",
   "Organization": "Delegation for relations with the countries of Southeast Asia and the Association of Southeast Asian Nations (ASEAN)",
   "start": "2013-10-09T00:00:00",
   "end": "2014-06-30T00:00:00",
   "term": 7,
   "abbr": "DASE"
  }
 ],
 "Staff": [
  {
   "role": "Member",
   "Organization": "Conference of Delegation Chairs",
   "start": "2006-03-21T00:00:00",
   "end": "2009-07-13T00:00:00",
   "term": 6
  }
 ],
 "Gender": "M",
 "CV": [
  "Mag.phil, PhD, Professor of Education at the Carinthia College of Education.",
  "Member of the European Parliament (since 4 April 2011); 1 February 2006 to 2009 and 1996 to 2004).",
  "Transport and security spokesman, ÖVP Delegation, European Parliament;",
  "security spokesman, ÖVP Delegation, European Parliament (2006-2009); security spokesman (coordinator), EPP Group (1999-2004); Deputy Head of ÖVP Delegation, European Parliament (1996-2004);",
  "Chair of the European Parliament Delegation for relations with the Korean Peninsula (2006-2009).",
  "Chair of the Initiative against Organized Crime (Stability Pact for South-East Europe) (2004-2006).",
  "Member of the Austrian Parliament (1990-1994).",
  "Regional Chair of the Austrian Employees' Federation(ÖAAB), Carinthia (1989-2009); Regional Party Chair, ÖVP Carinthia (2004-2009); ÖVP spokesman on security (1990-1994); ÖVP spokesman on EU security (1994-1996).",
  "Grand Gold Decoration with Ribbon for Services to the Republic of Austria."
 ],
 "changes": {
  "2012-03-09T18:01:40": [
   {
    "type": "added",
    "data": [
     {
      "Organization": "Transport and Tourism",
      "role": "Member",
      "abbr": "TRAN",
      "committee_id": "TRAN"
     },
     {
      "Organization": "Civil Liberties, Justice and Home Affairs",
      "role": "Substitute",
      "abbr": "LIBE",
      "committee_id": "LIBE"
     }
    ],
    "path": [
     "Committees"
    ]
   },
   {
    "type": "added",
    "data": {
     "Organization": "Delegation to the EU-Croatia Joint Parliamentary Committee",
     "role": "Substitute",
     "abbr": "D-HR"
    },
    "path": [
     "Delegations",
     0
    ]
   },
   {
    "type": "added",
    "data": {
     "Organization": "Delegation for relations with India",
     "role": "Substitute",
     "abbr": "D-IN"
    },
    "path": [
     "Delegations",
     1
    ]
   },
   {
    "type": "deleted",
    "data": {
     "Organization": "Delegation to the EU-Croatia Joint Parliamentary Committee",
     "role": "Substitute",
     "abbr": ""
    },
    "path": [
     "Delegations",
     0
    ]
   },
   {
    "type": "deleted",
    "data": {
     "Organization": "Delegation for relations with India",
     "role": "Substitute",
     "abbr": ""
    },
    "path": [
     "Delegations",
     1
    ]
   }
  ],
  "2013-07-21T22:44:49": [
   {
    "type": "changed",
    "data": [
     "9999-12-31T00:00:00",
     "2013-06-30T00:00:00"
    ],
    "path": [
     "Delegations",
     1,
     "end"
    ]
   }
  ],
  "2012-01-21T13:57:26": [
   {
    "data": [
     {
      "start": "2011-03-31T00:00:00",
      "role": "Member",
      "end": "9999-01-31T00:12:00",
      "groupid": "PPE",
      "Organization": "Group of the European People's Party (Christian Democrats)"
     }
    ],
    "type": "added",
    "path": [
     "Groups"
    ]
   },
   {
    "data": [
     {
      "end": "2014-01-31T00:06:00",
      "committee_id": "TRAN",
      "start": "2009-01-14T00:07:00",
      "role": "Member",
      "abbr": "TRAN",
      "Organization": "Transport and Tourism"
     },
     {
      "end": "2014-01-31T00:06:00",
      "committee_id": "LIBE",
      "start": "2009-01-14T00:07:00",
      "role": "Substitute",
      "abbr": "LIBE",
      "Organization": "Civil Liberties, Justice and Home Affairs"
     }
    ],
    "type": "added",
    "path": [
     "Committees"
    ]
   },
   {
    "data": {
     "aliases": [
      "Hubert PIRKER",
      "hubert pirker",
      "pirker",
      "HubertPIRKER",
      "hubertpirker",
      "pirker hubert",
      "PIRKER Hubert",
      "pirkerhubert",
      "PIRKER",
      "PIRKERHubert"
     ],
     "full": "Hubert PIRKER",
     "sur": "Hubert",
     "family": "PIRKER",
     "familylc": "pirker"
    },
    "type": "added",
    "path": [
     "Name"
    ]
   },
   {
    "data": "M",
    "type": "added",
    "path": [
     "Gender"
    ]
   },
   {
    "data": 2307,
    "type": "added",
    "path": [
     "UserID"
    ]
   },
   {
    "data": [
     "hubert.pirker@europarl.europa.eu"
    ],
    "type": "added",
    "path": [
     "Mail"
    ]
   },
   {
    "data": true,
    "type": "added",
    "path": [
     "active"
    ]
   },
   {
    "data": {
     "Brussels": {
      "Phone": "+322 28 45898",
      "Fax": "+322 28 49898",
      "Address": {
       "Building": "Bât. Altiero Spinelli",
       "City": "Bruxelles/Brussel",
       "Office": "08F143",
       "Zip": "B-1047",
       "building_code": "ASP",
       "Street": "60, rue Wiertz / Wiertzstraat 60",
       "Organization": "Parlement européen"
      }
     },
     "Postal": [
      "Europaïsches Parlament",
      "Rue Wiertz",
      "Altiero Spinelli 08F143",
      "B-1047 Brüssel"
     ],
     "Strasbourg": {
      "Phone": "+333 88 1 75898",
      "Fax": "+333 88 1 79898",
      "Address": {
       "Building": "Bât. Louise Weiss",
       "City": "Strasbourg",
       "Office": "T09055",
       "building_code": "LOW",
       "Street": "1, avenue du Président Robert Schuman",
       "Zip2": "F-67070",
       "Organization": "Parlement européen",
       "Zip1": "CS 91024"
      }
     }
    },
    "type": "added",
    "path": [
     "Addresses"
    ]
   },
   {
    "data": {
     "date": "1948-10-03T00:00:00",
     "place": "Gries"
    },
    "type": "added",
    "path": [
     "Birth"
    ]
   },
   {
    "data": "http://www.europarl.europa.eu/mepphoto/2307.jpg",
    "type": "added",
    "path": [
     "Photo"
    ]
   },
   {
    "data": [
     {
      "start": "2011-03-31T00:00:00",
      "end": "9999-01-31T00:12:00",
      "party": "Österreichische Volkspartei",
      "country": "Austria"
     }
    ],
    "type": "added",
    "path": [
     "Constituencies"
    ]
   },
   {
    "data": {
     "local": [
      "WUCHERER Michaela"
     ],
     "accredited": [
      "BERNHARD Karin",
      "MAICHER Melanie",
      "PRAMMER Simon"
     ]
    },
    "type": "added",
    "path": [
     "assistants"
    ]
   },
   {
    "data": [
     {
      "start": "2011-03-31T00:00:00",
      "end": "9999-01-31T00:12:00",
      "role": "Substitute",
      "abbr": "D-HR",
      "Organization": "Delegation to the EU-Croatia Joint Parliamentary Committee"
     },
     {
      "start": "2009-01-14T00:07:00",
      "end": "2014-01-31T00:06:00",
      "role": "Substitute",
      "abbr": "D-IN",
      "Organization": "Delegation for relations with India"
     }
    ],
    "type": "added",
    "path": [
     "Delegations"
    ]
   },
   {
    "data": [
     "http://www.europarl.europa.eu/rss/mep/hubert.pirker/en.xml"
    ],
    "type": "added",
    "path": [
     "RSS"
    ]
   },
   {
    "data": [
     "http://www.hubert-pirker.eu/"
    ],
    "type": "added",
    "path": [
     "Homepage"
    ]
   },
   {
    "data": [
     "Mag.phil, PhD, Professor of Education at the Carinthia College of Education.",
     "Member of the European Parliament (since 4 April 2011); 1 February 2006 to 2009 and 1996 to 2004).",
     "Transport and security spokesman, ÖVP Delegation, European Parliament;",
     "security spokesman, ÖVP Delegation, European Parliament (2006-2009); security spokesman (coordinator), EPP Group (1999-2004); Deputy Head of ÖVP Delegation, European Parliament (1996-2004);",
     "Chair of the European Parliament Delegation for relations with the Korean Peninsula (2006-2009).",
     "Chair of the Initiative against Organized Crime (Stability Pact for South-East Europe) (2004-2006).",
     "Member of the Austrian Parliament (1990-1994).",
     "Regional Chair of the Austrian Employees' Federation(ÖAAB), Carinthia (1989-2009); Regional Party Chair, ÖVP Carinthia (2004-2009); ÖVP spokesman on security (1990-1994); ÖVP spokesman on EU security (1994-1996).",
     "Grand Gold Decoration with Ribbon for Services to the Republic of Austria."
    ],
    "type": "added",
    "path": [
     "CV"
    ]
   },
   {
    "data": [
     {
      "start": "2011-03-31T00:00:00",
      "end": "9999-01-31T00:12:00",
      "role": "Member",
      "abbr": "PE",
      "Organization": "European Parliament"
     }
    ],
    "type": "added",
    "path": [
     "Staff"
    ]
   }
  ],
  "2012-04-02T15:57:32": [
   {
    "data": [
     "Civil Liberties, Justice and Home Affairs",
     "Committee on Civil Liberties, Justice and Home Affairs"
    ],
    "type": "changed",
    "path": [
     "Committees",
     2,
     "Organization"
    ]
   },
   {
    "data": [
     "Transport and Tourism",
     "Committee on Transport and Tourism"
    ],
    "type": "changed",

In [7]:
fields("ep_meps")

,field,present_%,type,example
0,UserID,100.0,int,2307
1,Name,100.0,dict,"{""full"": ""Hubert PIRKER"", ""sur"": ""Hubert"", ""family"": ""PIRKER"", ""aliases"": [""Hubert PIRKER"", ""PIRKER"", ""PIRKER Hubert""]}"
2,Photo,100.0,str,"""https://www.europarl.europa.eu/mepphoto/2307.jpg"""
3,meta,100.0,dict,"{""url"": ""http://www.europarl.europa.eu/meps/en/2307/name/cv"", ""updated"": ""2019-07-12T18:57:20""}"
4,active,100.0,bool,false
5,Constituencies,100.0,list,"[{""party"": ""Österreichische Volkspartei"", ""country"": ""Austria"", ""start"": ""1996-11-11T00:00:00"", ""end"": ""1999-07-19T0..."
6,changes,100.0,dict,"{""2012-03-09T18:01:40"": [{""type"": ""added"", ""data"": [{""Organization"": ""Transport and Tourism"", ""role"": ""Member"", ""abb..."
7,Groups,99.9,list,"[{""role"": ""Member"", ""Organization"": ""Group of the European People's Party (Christian-Democratic Group)"", ""groupid"": ..."
8,Birth,99.8,dict,"{""date"": ""1948-10-03T00:00:00"", ""place"": ""Gries""}"
9,Gender,99.8,str,"""M"""
10,Committees,98.5,list,"[{""role"": ""Member"", ""Organization"": ""Committee on Civil Liberties and Internal Affairs"", ""start"": ""1996-11-14T00:00:..."
11,Delegations,84.7,list,"[{""role"": ""Member"", ""Organization"": ""Delegation for relations with the Member States of ASEAN, South-east Asia and t..."
12,CV,46.5,list,"[""Mag.phil, PhD, Professor of Education at the Carinthia College of Education."", ""Member of the European Parliament ..."
13,Staff,11.2,list,"[{""role"": ""Member"", ""Organization"": ""Conference of Delegation Chairs"", ""start"": ""2006-03-21T00:00:00"", ""end"": ""2009-..."
14,Death,10.7,str,"""2014-05-12T00:00:00"""
15,Mail,2.4,list,"[""maurizioenzo.lupi@europarl.europa.eu""]"
16,Addresses,1.7,dict,"{""Brussels"": {""Phone"": ""0032 2 28 45810"", ""Fax"": ""0032 2 28 49810"", ""Address"": {""Organization"": ""Parlement européen""..."
17,assistants,1.6,dict,"{""accredited"": [""Ginta VANAGA""], ""local"": [""Armands APSITIS"", ""Ilmars DAMBE"", ""Edgars IKSTENS"", ""Martins LANGRATS"", ..."
18,Financial Declarations,1.5,list,"[{""mep_id"": ""111033"", ""url"": ""http://www.europarl.europa.eu/mepdif/111033_DFI_LEG8_rev0_LV.pdf"", ""date"": ""06/12/2018..."
19,Declaration on appropriate behaviour,1.4,list,"[{""title"": ""Declaration on appropriate behaviour (86 KB)"", ""url"": ""http://www.europarl.europa.eu/pdf/meps/appropriat..."
20,Declaration of private interests,1.2,list,"[{""title"": ""Original declaration - 16-01-2024 (85 KB)"", ""url"": ""https://www.europarl.europa.eu/erpl-app-public/mep-d..."
21,Declaration of good conduct,0.9,list,"[{""title"": ""Declaration of good conduct (PDF - 86 KB)"", ""url"": ""http://www.europarl.europa.eu/pdf/meps/appropriateBe..."
22,Homepage,0.9,list,"[""http://www.sergioberlato.it""]"
23,Declaration on awareness of conflicts of interest,0.9,list,"[{""title"": ""Declaration - Shadow rapporteur for opinion AGRI - 2024/2124(INI) - 20-10-2025 (80 KB)"", ""url"": ""https:/..."
24,Twitter,0.8,list,"[""http://twitter.com/Sadurskis""]"
25,Facebook,0.8,list,"[""https://www.facebook.com/SergioBerlato.paginaufficiale/""]"
26,Instagram,0.5,list,"[""https://www.instagram.com/berlato.sergio/""]"
27,Declarations of Participation,0.5,list,"[{""title"": ""Event - 27-02-2025 (26 KB)"", ""url"": ""https://www.europarl.europa.eu/erpl-app-public/mep-documents/DAT/10..."
28,X,0.3,list,"[""https://twitter.com/SERGIOBERLATO""]"
29,Voluntary confirmation on the use of the General Expenditure Allowance,0.1,list,"[{""title"": ""Voluntary confirmation III - 2026-07-17 (1 MB)"", ""url"": ""http://www.europarl.europa.eu/pdf/meps/geaDecla..."
30,LinkedIn,0.1,list,"[""https://es.linkedin.com/in/pablo-arias-14b18025""]"
31,_id,0.1,str,"""53b2dd18b819f205b00000b7"""
32,Blog,0.1,list,"[""http://www.sergioberlato.it/""]"
33,Youtube,0.1,list,"[""https://www.youtube.com/channel/UCouduwQiq2AK5KzJU9tUR-g""]"
34,Telegram,0.1,list,"[""https://t.me/fabiennekeller""]"

## `ep_dossiers`

In [8]:
show_raw("ep_dossiers", n=1)

===== ep_dossiers: first 1 records =====
{
 "activities": [
  {
   "date": "2011-03-28T00:00:00",
   "docs": [
    {
     "text": [
      "<div id=\"summary\">\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">PURPOSE: to submit to the EU legislature draft\namendments to the Statute of the Court of Justice and Annex I\nthereto.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">PROPOSED ACT: Regulation of the European Parliament\nand of the Council.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">LEGAL BASIS: Article 19(2), second paragraph, of the\nTreaty on the Functioning of the European Union. (TFUE); first\nparagraph of Article 254, the first and second paragraphs of\nArticle 257 and the second paragraph of Article 281 TFEU; Article\n106a(1) of the Treaty establishing the European Atomic Energy\nCommunity. &#160;</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">CONTENT:&#160;the <b>Court of Justice submits to the\nEuropean Union legislature</b> draft amendments to the Statute of\nthe Court of Justice and its Annex I. This single text incorporates\nseparate proposals in respect of each of the three jurisdictions\nwhich comprise the Court of Justice of the European\nUnion.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><b><span lang=\"EN-GB\">1) Proposals relating to the Court of\nJustice</span></b><span lang=\"EN-GB\">: the Court considers it\ndesirable to establish the office of Vice-President of the Court of\nJustice and to amend the rules relating to the composition of the\nGrand Chamber.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">The current structure of the Grand Chamber and the\nrules determining how it operates - a quorum of nine Judges\ntogether with the participation in every case of the President of\nthe Court and the Presidents of the Chambers of five Judges - are\nthe product of amendments introduced by the Treaty of Nice, which\nentered into force on 1 February 2003.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">Since that date, there have been a number of changes\naffecting the work of the Court: (i) the accession of 12 new Member\nStates; (ii) the transition from two to three Chambers of five\nJudges in May 2004 and to four Chambers of five Judges in October\n2006; (iii) the introduction of the urgent preliminary ruling\nprocedure in March 2008; and (iv) the introduction of the review\nprocedure following the establishment of the Civil Service\nTribunal.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">At present, the President of the Court and the\nPresidents of the Chambers of five Judges have a very heavy\nworkload, whereas other Judges sit in relatively few cases assigned\nto the Grand Chamber.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\">The proposal\nprovides for&#160;:</p>\n<ul style=\"margin-top:0cm\" type=\"disc\">\n<li style=\"text-align:justify\" class=\"MsoNormal\"><b><span lang=\"EN-GB\">broader participation by the Judges in cases assigned\nto the Grand Chamber</span></b><span lang=\"EN-GB\">, allowing them\nto sit far more frequently than at present (in almost half, instead\nof a third, of all cases). That would be achieved by the amendment\nof Articles 16 and 17 of the Statute so as to increase to 15 the\nnumber of Judges constituting the Grand Chamber and to end the\nautomatic participation of the Presidents of Chambers of five\nJudges in Grand Chamber cases. Corresponding adjustments must be\nmade to the rules relating to the quorum of the Grand Chamber and\nof the full Court;</span></li>\n<li style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">the <b>establishment of the office of\nVice-President</b>: the latter would sit, like the President, in\nevery case assigned to the Grand Chamber. The permanent presence of\ntwo persons, together with the more frequent participation of the\nother Judges in the work of the Grand Chamber, would ensure that\nits case-law is consistent. In addition to sitting in every Grand\nChamber case, the Vice-President would also assist the President of\nthe Court in his duties.</span></li>\n</ul>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><b><span lang=\"EN-GB\">2) Proposals relating to the General\nCourt</span></b><span lang=\"EN-GB\">: for several years now, the\nnumber of cases disposed of by the General Court has been lower\nthan the number of new cases, so that the number of pending cases\nis rising constantly. At the end of 2010, there were 1&#160;300\ncases pending, whereas, in the same year, 527 cases were disposed\nof.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">In addition to the number of cases currently pending,\nthe likely increase in the number of cases brought before the\nGeneral Court must be taken into account: there was an <b>increase\nof 65% between 2000 and 2010</b>. &#160;In addition to those areas\nof litigation, further litigation will be generated by the\napplication of the numerous regulations establishing European Union\nagencies, in particular the REACH Regulation <b>The current\nincrease in workload is due to</b> (i) the devolution of\njurisdiction, since 2004, to rule on certain classes of action or\nproceedings brought by the Member States; (ii) to the increase in\nlitigation following the 2004 and 2007 accessions; (iii) to the\nlitigation engendered by the increase, resulting from greater\nEuropean integration, in the number and variety of legislative and\nregulatory acts of the institutions, bodies, offices and agencies\nof the EU; and (iv) to the growth of litigation relating to\nCommunity trade mark applications.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">The Court of Justice believes that a structural\nsolution is urgently required.&#160; The Treaties offer <b>two\npossible routes to reform</b>:</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">(a) to establish specialised courts with jurisdiction\nto hear and determine direct actions in a specific area, in\naccordance with the first paragraph of Article 257&#160;TFEU. The\nfield of intellectual property has been mooted in that regard; (b)\nincreasing the number of Judges of the General Court by means of an\namendment to Article 48&#160;of the Statute in accordance with the\nmechanism provided for in the second paragraph of Article\n281&#160;TFEU.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">Having weighed up the two options at length, <b>the\nCourt of Justice has come to the conclusion that an increase in the\nnumber of Judges is clearly preferable to the establishment of a\nspecialised court in the field of intellectual property</b>. Its\nreasons relate to the effectiveness of the proposed solution, the\nurgency of the situation, the flexibility of the measure envisaged\nand the consistency of European Union law.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">The Court of Justice therefore considers that <b>an\nincrease in the number of Judges by at least 12</b>, bringing the\nnumber of General Court Judges to <b>39</b>, is\nnecessary.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><b><span lang=\"EN-GB\">3) Proposals relating to the Civil Service\nTribunal</span></b><span lang=\"EN-GB\">: the European Union Civil\nService Tribunal comprises seven Judges. Owing to that limited\ncomposition, the functioning of the Tribunal can be seriously\naffected if one of its members, for an extended period of time, is\nprevented on medical grounds from performing his duties, without\nhowever suffering from disablement within the meaning of Article 10\nof Council Regulation No&#160;422/67/EEC,\nNo&#160;5/67/Euratom.&#160;</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">In order to ensure that the Civil Service Tribunal is\nnot placed in a situation of difficulty such as to prevent it from\ncarrying out its judicial functions, it is proposed to amend\nArticle 62c of the Statute of the Court by providing, in general\nterms, for the <b>possibility of attaching temporary Judges</b> to\nthe specialised courts.</span></p>\n<p style=\"text-align:justify\" class=\"MsoNormal\"><span lang=\"EN-GB\">The rules governing the appointment of temporary\nJudges, their rights and obligations, the conditions under which\nthey are to perform their duties and the circumstances in which\nthey will cease to perform those duties are laid down in a <span style=\"color:blue\"><a href=\"http://www.europarl.europa.eu/oeil/FindByProcnum.do?lang=en&amp;procnum=COD/2011/0902\"><span style=\"color:blue\">separate draft regulation</span></a></span>,\nwhich would supplement Annex I to the Statute.</span></p>\n</div>\n"
     ],
     "type": "Legislative proposal published",
     "title": "02074/2011"
    }
   ],
   "body": "EC",
   "commission": [
    {
     "DG": {
      "url": "http://ec.europa.eu/dgs/legal_service/",
      "title": "Legal Service"
     },
     "Commissioner": "BARROSO José Manuel"
    }
   ],
   "type": "Legislative proposal"
  },
  {
   "date": "2011-04-07T00:00:00",
   "body": "EP",
   "type": "Committee referral announced in Parliament, 1st reading/single reading",
   "committees": [
    {
     "body": "EP",
     "responsible": false,
     "committee": "AFCO",
     "date": "2011-07-12T00:00:00",
     "committee_full": "Constitutional Affairs",
     "rapporteur": [
      {
       "group": "EFD",
       "name": "MESSERSCHMIDT Morten",
       "mepref": "4de186fd0fb8127435bdc12a"
      }
     ]
    },
    {
     "body": "EP",
     "responsible": false,
     "committee": "BUDG",
     "date": "2011-09-28T00:00:00",
     "committee_full": "Budgets",
     "rapporteur": [
      {
       "group": "NI",
       "name": "WERTHMANN Angelika",
       "mepref": "4de1896c0fb8127435bdc49c"
      }
     ]
    },
    {
     "body": "EP",
     "shadows": [
      {
       "group": "EPP",
       "name": "ZWIEFKA Tadeusz",
       "mepref": "4de1898b0fb8127435bdc4c5"
      },
      {
       "group": "S&D",
       "name": "MASIP HIDALGO Antonio",
       "mepref": "4de186db0fb8127435bdc100"
      },
      {
       "group": "Verts/ALE",
       "name": "LICHTENBERGER Eva",
       "mepref": "4de186570fb8127435bdc043"
      },
      {
       "group": "ECR",
       "name": "ZIOBRO Zbigniew",
       "mepref": "4de189910fb8127435bdc4cc"
      },
      {
       "group": "GUE/NGL",
       "name": "MAŠTÁLKA Jiří",
       "mepref": "4de186c20fb8127435bdc0db"
      },
      {
       "group": "EFD",
       "name": "SPERONI Francesco Enrico",
       "mepref": "4de188260fb8127435bdc2d0"
      }
     ],
     "responsible": true,
     "committee": "JURI",
     "date": "2011-04-12T00:00:00",
     "committee_full": "Legal Affairs",
     "rapporteur": [
      {
       "group": "ALDE",
       "name": "THEIN Alexandra",
       "mepref": "4de188ea0fb8127435bdc3ee"
      }
     ]
    }
   ]
  },
  {
   "date": "2011-09-30T00:00:00",
   "docs": [
    {
     "url": "http://eur-lex.europa.eu/smartapi/cgi/sga_doc?smartapi!celexplus!prod!DocNumber&lg=EN&type_doc=COMfinal&an_doc=2011&nu_doc=596",
     "text": [
      "<div id=\"summary\">\n<p class=\"MsoNormal\"><span lang=\"EN-GB\">The Commission presents its\nOpinion on the requests for the amendment of the Statute of the\nCourt of Justice of the EU, presented by the Court in two requests\non 28 March 2011. The proposed amendments concern to varying\ndegrees the three courts currently making up the Court of Justice\nof the European Union: the Court of Justice, the General Court and\nthe Civil Service Tribunal. The Court also proposes an amendment\nthat would affect the three courts in the same way, namely dropping\nthe provision on periods of grace based on considerations of\ndistance, which would in fact result in the disappearance of the\nten-day fixed period which is currently added to the procedural\ndeadlines. Following the entry into force of the Lisbon Treaty,\nthese provisions should, for the first time, be adopted by the\nEuropean Parliament and the Council, acting in accordance with the\nordinary legislative procedure.</span></p>\n<p class=\"MsoNormal\"><b><span lang=\"EN-GB\">Court of\nJustice</span></b><span lang=\"EN-GB\">: the amendments are intended\nto:</span></p>\n<ul style=\"margin-top:0cm\" type=\"disc\">\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">establish the office of\nVice-President of the Court and to determine the tasks to be\nentrusted to him/her;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">modify the composition of\nthe Grand Chamber;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">increase the quorum for\ndecisions by the Grand Chamber and the full Court;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">abolish the reading at the\nhearing of the report presented by the\nJudge-Rapporteur.</span></li>\n</ul>\n<p class=\"MsoNormal\"><span lang=\"EN-GB\">The Commission supports all\nthe proposals made in relation to the Court of Justice, but\nsuggests:</span></p>\n<ul style=\"margin-top:0cm\" type=\"disc\">\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">stating in which cases the\nPresident&#160; of the Court can be replaced by the\nVice-President;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">ensuring more stability in\nthe composition of the enlarged Grand Chamber. The Commission\nsuggests a rule that three Presidents of Chambers of five Judges\nmust always form part of this Grand Chamber. The Rules of Procedure\nwould contain conditions governing the participation of judges in\neach case, probably involving a system of two rotating lists\n(instead of a single list as is the case at the moment): one\nconsisting of the Presidents of the Chambers of five Judges and the\nsecond one consisting of the other judges.</span></li>\n</ul>\n<p class=\"MsoNormal\"><b><span lang=\"EN-GB\">The General\nCourt</span></b><span lang=\"EN-GB\">: in order to cope with the\nincrease in its caseload and the resulting increase in the time\ntaken to handle cases, it is proposed that the number of judges be\nincreased to 39. The Commission approves the amendments, subject to\ncomments and proposals regarding:</span></p>\n<ul style=\"margin-top:0cm\" type=\"disc\">\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">the replacement of\njudges;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">the number of specialised\nchambers, with a minimum of two;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">the need for an office of\nVice-President of the General Court, as proposed for the Court of\nJustice;</span></li>\n<li class=\"MsoNormal\"><span lang=\"EN-GB\">a transitional provision\nstating that the new judges will take up their posts immediately\nbefore their first six-year term has formally started, and . also\ndetermining the effective duration of terms of each new\njudge;</span></li>\n</ul>\n<p class=\"MsoNormal\"><b><span lang=\"EN-GB\">Civil Service\nTribunal</span></b><span lang=\"EN-GB\">: the Court requests that it\nbe assigned three temporary judges upon whom it could call in the\nevent that a judge is prevented from attending for a long period of\ntime. The Commission approves the amendments, subject to comments\non the need to lay down the order in which the three temporary\njudges are required to undertake judicial duties when, in\naccordance with the conditions laid down, one of the member judges\nis unable to attend.</span></p>\n<p class=\"MsoNormal\"><span lang=\"EN-GB\">The Court proposes that in\nthe event of the return of the judge who was absent, the Tribunal\ncan decide on a discretionary basis that a temporary judge should\ncontinue to perform his duties until the cases in which he has been\nsitting are completed. The Commission has some criticism to make\nabout this approach since it could weaken the independence of\ntemporary judges given that the permanent judges with whom they\nwork would decide whether or not they continue to perform their\nduties. For this reason, it considers that it would be more\nappropriate to adopt an objective criterion to determine the cases\nwhich the temporary judge would continue to handle even after the\nreturn of the judge he is replacing.</span></p>\n<p class=\"MsoNormal\"><b><span lang=\"EN-GB\">Amendments relating to\nall three Courts</span></b><span lang=\"EN-GB\">: lastly, the Court\nproposes dropping the&#160; provision on the ten-day fixed period\nof grace based on considerations of distance on the grounds that it\nis no longer justified in this era of new technology. The\nCommission states that if the ten-day grace period is dropped, it\nwould recommend extending some specific periods set down in the\nStatute, amongst them, the period set down for submitting written\nobservations on cases referred to the Court of Justice, and the\nperiod for appealing against certain decisions of the General Court\nand of the Civil Service Tribunal.</span></p>\n<p style=\"font-weight: bold\" class=\"MsoNormal\"><span lang=\"EN-GB\">&#160;</span></p>\n</div>\n"
     ],
     "title": "COM(2011)0596",
     "type": "Document attached to the procedure",
     "celexid": "CELEX:52011DC0596:EN"
    }
   ],
   "body": "EC",
   "commission": [
    {
     "DG": {
      "url": "http://ec.europa.eu/dgs/legal_service/",
      "title": "Legal Service"
     },
     "Commissioner": "BARROSO José Manuel"
    }
   ],
   "type": "Document attached to the procedure"
  },
  {
   "date": "2011-11-29T00:00:00",
   "docs": [
    {
     "url": "http://www.europarl.europa.eu/sides/getDoc.do?type=COMPARL&mode=XML&language=EN&reference=PE475.771",
     "type": "Committee draft report",
     "title": "PE475.771"
    }
   ],
   "body": "EP",
   "type": "Committee draft report"
  },
  {
   "date": "2011-12-05T00:00:00",
   "body": "CSL",
   "type": "Council Meeting",
   "council": "General Affairs",
   "meeting_id": "3132"
  },
  {
   "date": "2012-05-31T00:00:00",
   "body": "EP",
   "type": "Vote in committee, 1st reading/single reading",
   "committees": [
    {
     "body": "EP",
     "responsible": false,
     "committee": "AFCO",
     "date": "2011-07-12T00:00:00",
     "committee_full": "Constitutional Affairs",
     "rapporteur": [
      {
       "group": "EFD",
       "name": "MESSERSCHMIDT Morten",
       "mepref": "4de186fd0fb8127435bdc12a"
      }
     ]
    },
    {
     "body": "EP",
     "responsible": false,
     "committee": "BUDG",
     "date": "2011-09-28T00:00:00",
     "committee_full": "Budgets",
     "rapporteur": [
      {
       "group": "NI",
       "name": "WERTHMANN Angelika",
       "mepref": "4de1896c0fb8127435bdc49c"
      }
     ]
    },
    {
     "body": "EP",
     "shadows": [
      {
       "group": "EPP",
       "name": "ZWIEFKA Tadeusz",
       "mepref": "4de1898b0fb8127435bdc4c5"
      },
      {
       "group": "S&D",
       "name": "MASIP HIDALGO Antonio",
       "mepref": "4de186db0fb8127435bdc100"
      },
      {
       "group": "Verts/ALE",
       "name": "LICHTENBERGER Eva",
       "mepref": "4de186570fb8127435bdc043"
      },
      {
       "group": "ECR",
       "name": "ZIOBRO Zbigniew",
       "mepref": "4de189910fb8127435bdc4cc"
      },
      {
       "group": "GUE/NGL",
       "name": "MAŠTÁLKA Jiří",
       "mepref": "4de186c20fb8127435bdc0db"
      },
      {
       "group": "EFD",
       "name": "SPERONI Francesco Enrico",
       "mepref": "4de188260fb8127435bdc2d0"
      }
     ],
     "responsible": true,
     "committee": "JURI",
     "date": "2011-04-12T00:00:00",
     "committee_full": "Legal Affairs",
     "rapporteur": [
      {
       "group": "ALDE",
       "name": "THEIN Alexandra",

In [9]:
fields("ep_dossiers")

,field,present_%,type,example
0,meta,100.0,dict,"{""source"": ""http://www.europarl.europa.eu/oeil/popups/ficheprocedure.do?reference=2011/0901(COD)"", ""updated"": ""2012-..."
1,changes,100.0,dict,"{""2012-04-01T23:37:53"": [{""data"": ""http://www.europarl.europa.eu/sides/getDoc.do?type=COMPARL&mode=XML&language=EN&r..."
2,procedure,100.0,dict,"{""dossier_of_the_committee"": ""JURI/7/05776"", ""reference"": ""2011/0901(COD)"", ""subtype"": ""Legislation"", ""title"": ""Cour..."
3,events,93.8,list,"[{""date"": ""2014-01-08T00:00:00"", ""type"": ""Legislative proposal published"", ""body"": ""EC"", ""docs"": [{""url"": ""http://re..."
4,docs,80.0,list,"[{""date"": ""2014-01-08T00:00:00"", ""docs"": [{""url"": ""http://register.consilium.europa.eu/content/out?lang=EN&typ=SET&i..."
5,committees,73.8,list,"[{""body"": ""EP"", ""responsible"": false, ""committee"": ""AFCO"", ""date"": ""2011-07-12T00:00:00"", ""committee_full"": ""Constit..."
6,commission,53.1,list,"[{""body"": ""EC"", ""dg"": ""Economic and Financial Affairs"", ""commissioner"": ""REHN Olli""}]"
7,council,25.2,list,"[{""body"": ""CSL"", ""type"": ""Council Meeting"", ""council"": ""Economic and Financial Affairs ECOFIN"", ""meeting_id"": ""3324""..."
8,links,24.1,dict,{}
9,otherinst,8.7,list,"[{""name"": ""European Economic and Social Committee""}]"
10,activities,6.1,list,"[{""date"": ""2011-03-28T00:00:00"", ""docs"": [{""text"": [""<div id=\""summary\"">\n<p style=\""text-align:justify\"" class=\""M..."
11,_id,6.1,str,"""4f33d5fbb819f2756a000016"""
12,other,6.1,list,"[{""body"": ""EC"", ""dg"": {""url"": ""http://ec.europa.eu/dgs/legal_service/"", ""title"": ""Legal Service""}, ""commissioner"": ""..."

## AI Act subset as a table
Amendments for one procedure, flattened into a DataFrame (all raw fields kept as columns).

In [10]:
REF = "2021/0106(COD)"
rows = [r for r in records("ep_amendments") if r.get("reference") == REF]
df = pd.json_normalize(rows)
print(len(df), "amendments")
print(list(df.columns))
df.head(10)

4852 amendments
['src', 'peid', 'reference', 'date', 'committee', 'seq', 'id', 'orig_lang', 'old', 'new', 'authors', 'meps', 'location', 'meta.created', 'compromise', 'justification']

,src,peid,reference,date,committee,seq,id,orig_lang,old,new,authors,meps,location,meta.created,compromise,justification
0,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],68,PE704.585-68,en,"[(1) The purpose of this Regulation is to, improve the functioning of the internal, market by laying down a uniform ...","[(1) The purpose of this Regulation is to, improve the functioning of the internal, market by laying down a uniform ...","César Luena, Javi López, Cyrus Engerer, Milan Brglez","[197721, 125042, 209091, 197446]","[[Proposal for a regulation, Recital 1]]",2022-02-24T00:23:49,NaN,NaN
1,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],69,PE704.585-69,en,"[(1) The purpose of this Regulation is to, improve the functioning of the internal, market by laying down a uniform ...","[(1) The purpose of this Regulation is to, improve the functioning of the internal, market by laying down a uniform ...",Margrete Auken on behalf of the Greens/EFA Group,[28161],"[[Proposal for a regulation, Recital 1]]",2022-02-24T00:23:49,NaN,NaN
2,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],70,PE704.585-70,en,NaN,"[(1 a) This Regulation should foster a, supportive environment for healthier, lifestyles in a sustainable and climat...",Margrete Auken on behalf of the Greens/EFA Group,[28161],"[[ Proposal for a regulation, Recital 1 a (new)]]",2022-02-24T00:23:49,NaN,NaN
3,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],71,PE704.585-71,en,"[(2) Artificial intelligence systems (AI, systems) can be easily deployed in multiple, sectors of the economy and so...","[(2) Artificial intelligence systems (AI, systems) can be easily deployed in multiple, sectors of the economy and so...","César Luena, Javi López, Cyrus Engerer, Milan Brglez","[197721, 125042, 209091, 197446]","[[ Proposal for a regulation, Recital 2]]",2022-02-24T00:23:49,NaN,NaN
4,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],72,PE704.585-72,en,"[(3) Artificial intelligence is a fast, evolving family of technologies that can, contribute to a wide array of econ...","[(3) Artificial intelligence is a fast, evolving family of technologies that can, contribute to a wide array of econ...",Margrete Auken,[28161],"[[ Proposal for a regulation, Recital 3]]",2022-02-24T00:23:49,[ on behalf of the Greens/EFA Group],NaN
5,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],73,PE704.585-73,en,"[(3) Artificial intelligence is a fast, evolving family of technologies that can, contribute to a wide array of econ...","[(3) Artificial intelligence is a fast, evolving family of technologies that can, contribute to a wide array of econ...",Michal Wiezik,[197769],"[[ Proposal for a regulation, Recital 3]]",2022-02-24T00:23:49,NaN,NaN
6,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],74,PE704.585-74,en,"[(3) Artificial intelligence is a fast, evolving family of technologies that can, contribute to a wide array of econ...","[(3) Artificial intelligence is a fast, evolving family of technologies that can, contribute to a wide array of econ...","César Luena, Javi López, Cyrus Engerer, Milan Brglez","[197721, 125042, 209091, 197446]","[[Proposal for a regulation, Recital 3]]",2022-02-24T00:23:49,NaN,NaN
7,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],75,PE704.585-75,en,NaN,"[(3 a) In order to ensure the dual, ecological and digital transition, secure, the technological resilience of the U...","Marie Toussaint, David Cormand","[97236, 197503]","[[ Proposal for a regulation, Recital 3 a (new)]]",2022-02-24T00:23:50,NaN,NaN
8,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],76,PE704.585-76,en,NaN,"[(3 a) AI can serve in climate change, mitigation for example through the, European Union's Earth observation, progr...","Sirpa Pietikäinen, Deirdre Clune, Joanna Kopcińska","[40599, 124988, 197530]","[[ Proposal for a regulation, Recital 3 a (new)]]",2022-02-24T00:23:50,NaN,NaN
9,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf,PE704.585v01-00,2021/0106(COD),2022-01-25T00:00:00,[ENVI],77,PE704.585-77,en,NaN,"[(3 a) Advanced AI solutions for, medicines and healthcare should support, the fight against disinformation to secur...",Margrete Auken on behalf of the Greens/EFA Group,[28161],"[[Proposal for a regulation, Recital 3 a (new)]]",2022-02-24T00:23:50,NaN,Disinformation around vaccines in particular is just one example of cyber-disinformation\nundermining public trust a...

In [11]:
# one amendment in full, with the text lines joined
r = rows[0]
for k, v in r.items():
    print(f"{k:15} {' '.join(v) if k in ('old', 'new') and isinstance(v, list) else v}")

src             https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf
peid            PE704.585v01-00
reference       2021/0106(COD)
date            2022-01-25T00:00:00
committee       ['ENVI']
seq             68
id              PE704.585-68
orig_lang       en
old             (1) The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform legal framework in particular for the development, marketing and use of artificial intelligence in conformity with Union values. This Regulation pursues a number of overriding reasons of public interest, such as a high level of protection of health, safety and fundamental rights, and it ensures the free movement of AI- based goods and services cross-border, thus preventing Member States from imposing restrictions on the development, marketing and use of AI systems, unless explicitly authorised by this Regulation.
new             (1) The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform legal framework for the design, development, marketing and use of artificial intelligence and of sustainable and green artificial intelligence in conformity with Union values while minimising any risk of adverse and discriminatory impacts on people and adverse impacts on the environment. This Regulation pursues a number of overriding reasons of public interest, such as a high level of protection of health, safety, and fundamental rights, and the protection of environment and it ensures the free movement of AI-based goods and services cross-border, thus preventing Member States from imposing restrictions on the design, development, marketing and use of AI systems, unless explicitly authorised by this Regulation.
authors         César Luena, Javi López, Cyrus Engerer, Milan Brglez
meps            [197721, 125042, 209091, 197446]
location        [['Proposal for a regulation', 'Recital 1']]
meta            {'created': '2022-02-24T00:23:49'}
changes         {}

## Output files from `build_dashboard.py` (if already run)

In [12]:
for p in sorted(Path("output").glob("*.csv")):
    out = pd.read_csv(p)
    print(p, out.shape)
    print(list(out.columns))
    display(out.head(5))

output/amendments_2021_0106_COD.csv (4852, 17)
['id', 'pe', 'seq', 'date', 'committee', 'location', 'provision', 'is_new', 'deletion', 'authors', 'mep_names', 'groups', 'old', 'new', 'added_words', 'justification', 'src']

,id,pe,seq,date,committee,location,provision,is_new,deletion,authors,mep_names,groups,old,new,added_words,justification,src
0,PE704.585-68,PE704.585v01-00,68,2022-01-25,ENVI,Recital 1,Recital 1,False,False,"César Luena, Javi López, Cyrus Engerer, Milan Brglez",César LUENA; Javi LÓPEZ; Cyrus ENGERER; Milan BRGLEZ,S&D; S&D; S&D; S&D,(1) The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform leg...,(1) The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform leg...,"design, … and of sustainable and green artificial intelligence … values while minimising any risk of adverse and dis...",NaN,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf
1,PE704.585-69,PE704.585v01-00,69,2022-01-25,ENVI,Recital 1,Recital 1,False,False,Margrete Auken on behalf of the Greens/EFA Group,Margrete AUKEN,Greens/EFA,(1) The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform leg...,(1) The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform leg...,"priorities and … biodiversity, the climate and the environment,",NaN,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf
2,PE704.585-70,PE704.585v01-00,70,2022-01-25,ENVI,Recital 1 a (new),Recital 1 a (new),True,False,Margrete Auken on behalf of the Greens/EFA Group,Margrete AUKEN,Greens/EFA,NaN,(1 a) This Regulation should foster a supportive environment for healthier lifestyles in a sustainable and climate n...,(1 a) This Regulation should foster a supportive environment for healthier lifestyles in a sustainable and climate n...,NaN,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf
3,PE704.585-71,PE704.585v01-00,71,2022-01-25,ENVI,Recital 2,Recital 2,False,False,"César Luena, Javi López, Cyrus Engerer, Milan Brglez",César LUENA; Javi LÓPEZ; Cyrus ENGERER; Milan BRGLEZ,S&D; S&D; S&D; S&D,(2) Artificial intelligence systems (AI systems) can be easily deployed in multiple sectors of the economy and socie...,(2) Artificial intelligence systems (AI systems) can be easily deployed in multiple sectors of the economy and socie...,"persons, end users and end recipients",NaN,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf
4,PE704.585-72,PE704.585v01-00,72,2022-01-25,ENVI,Recital 3,Recital 3,False,False,Margrete Auken,Margrete AUKEN,Greens/EFA,(3) Artificial intelligence is a fast evolving family of technologies that can contribute to a wide array of economi...,(3) Artificial intelligence is a fast evolving family of technologies that can contribute to a wide array of economi...,"food safety, by reducing the use of pesticides, the conservation and restoration of biodiversity and ecosystems, acc...",NaN,https://www.europarl.europa.eu/doceo/document/ENVI-AM-704585_EN.pdf

## Have Your Say feedback (if `fetch_feedback.py` was run)

In [13]:
for p in sorted(Path("feedback").glob("*/feedback.csv")):
    fb = pd.read_csv(p)
    print(p, fb.shape)
    print(list(fb.columns))
    display(fb.head(5))